CREATE TABLE users(
	id UUID,
	username VARCHAR(150) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	user_password VARCHAR(255) NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	CONSTRAINT pk_user_id PRIMARY KEY(id)
);

-- 2. Table roles (The IDs are auto-incrementing)
CREATE TABLE roles(
	id INT GENERATED ALWAYS AS IDENTITY,
	rol_name VARCHAR(75) NOT NULL UNIQUE,
	CONSTRAINT pk_rol_id PRIMARY KEY (id)
);

-- 3. Table permissions (The IDs are auto-incrementing)
CREATE TABLE permissions(
	id INT GENERATED ALWAYS AS IDENTITY,
	name_permission VARCHAR(125) NOT NULL UNIQUE,
	CONSTRAINT pk_permission_id PRIMARY KEY (id)
);

-- 4. Table users_roles
CREATE TABLE users_roles(
	user_id UUID NOT NULL,
	rol_id INT NOT NULL,
	PRIMARY KEY (user_id, rol_id),
	CONSTRAINT fk_user_rol_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	CONSTRAINT fk_user_rol_rol FOREIGN KEY (rol_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- 5. Table roles_permissions
CREATE TABLE roles_permissions(
	rol_id INT NOT NULL,
	permission_id INT NOT NULL,
	PRIMARY KEY (rol_id, permission_id),
	CONSTRAINT fk_rol_permission_rol FOREIGN KEY (rol_id) REFERENCES roles(id) ON DELETE CASCADE,
	CONSTRAINT fk_rol_permission_permission FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

-- 6. Table refresh_tokens (IDs are also generated by domain layer)
CREATE TABLE refresh_tokens(
	id UUID PRIMARY KEY,
	user_id UUID NOT NULL,
	token_hash VARCHAR(255) NOT NULL UNIQUE,
	expiration_date TIMESTAMP NOT NULL,
	is_revoked BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	CONSTRAINT fk_rt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);


-- 7. Table user_details (1:1 relationship with the user; uses the same user ID)
CREATE TABLE user_details(
	user_id UUID PRIMARY KEY,
	user_name VARCHAR(200) NOT NULL,
	last_name VARCHAR(200) NOT NULL,
	age SMALLINT NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	CONSTRAINT fk_user_details_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 8. Create indexes for essential performance
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_token_hash ON refresh_tokens(token_hash);
